theme: jekyll-theme-minimal
title: Levin Hornischer
description: Assistant professor at [MCMP](https://www.mcmp.philosophie.uni-muenchen.de/people/faculty/hornischer_levin/index.html), LMU Munich
logo: /pics/picture.jpg
